[package]
name = "unused-export-lint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
tree-sitter = "0.20.9"
tree-sitter-typescript = "0.20.1"
